# -*- coding: utf-8 -*-
"""definiciones_pda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uu2JT_NKEAxWv-fhYOw82KOjsTzZHIv7
"""

def sumar(a, b):
  suma = a + b
  return(suma)

num1 = int(input("Ingrese primer numero: "))
num2 = int(input("Ingrese segundo numero: "))
print(f"El resultado de la suma es: ", sumar(num1, num2))

def varios_valores(*args):
  for arg in args:
    print(arg)

varios_valores(4.5, "Buen dia",[1, 2, 3, 4, 5])

#Ejercicio 2
def resta(a, b):
  return a - b

resta(b = 30, a = 10)

def calcular_iva(precio):
  iva = 0.19
  return precio*iva

precio = float(input("Valor producto: "))
print("El IVA a pagar es de: ", str(calcular_iva(precio)))

def descuento(prod, desc):
  v_final = prod - (prod*desc/100)
  return v_final

productos = [1000, 50]

print("El valor de producto con el descuento es de: ", str(descuento(*productos)))

def descuento(prod, desc):
  v_final = prod - (prod*desc/100)
  return v_final

chocman = "Chocman de oro"
producto = 1_000_000
cant_descuento = 99
print(f"El valor final del {chocman} con descuento de {cant_descuento}% : ", str(descuento(producto, cant_descuento)))

def descuento(prod, desc):
  v_final = prod - (prod*desc/100)
  return v_final

chocman = "Chocman de oro"
producto = float(input("Ingrese el valor del producto: "))
cant_descuento = float(input("Ingrese el descuento a agregar: "))
print(f"El valor final del {chocman} con descuento de {cant_descuento}% : ", str(descuento(producto, cant_descuento)))

def calcular_imc(peso, altura):
  imc = peso / altura ** 2
  return imc

peso = float(input("Ingrese su peso: "))
altura = float(input("Ingrese su altura: "))
print("Su indice de masa corporal es de: ", str(calcular_imc(peso, altura)))

"""Hacer el menu entero,juntar todos los cosas"""

def suma():
  var1 = 10
  var2 = 20
  total = var1 + var2
  print(f"Resultado es: ", total)

suma()

def suma():
  var1 = 10
  var2 = 20
  total = var1 + var2
  return total

print("texto", suma())

# busque el codigo tanto de producto y despliegue descripcio y precio.

def suma(var1, var2):
  total = var1 + var2
  return total

var1 = 10
var2 = 20
print("Resultado: ", suma(var1, var2))

"""un local de comida para mascotas necesita capturar los pedidos de sus clientes, para saber cual  cuales son los productos más vendidos en un dia.
tabla de productos
"""

producto = [["01001", "catshaw 10kg", 1, 25_500],
            ["01002", "Fitformula 10kg", 1, 29_600],
            ["01003", "Cachupin gato 20kg", 1, 18_500],
            ["01004", "purofilete 10kg", 1, 58_600]]

"""Se debe permitir eliminar un pedido, emitir una boleta, emitir reporte de productos más vendidos.
ultilizar sistema menú, funciones, arreglos o listas, validacion de errores.
"""

import numpy as np

def menu_principal():
  print("1.- Catshaw 10kg.")
  print("2.- Fitformula 10kg")
  print("3.- Fitformula 10kg")
  print("4.- Fitformula 10kg")
  selec = int(input("Escoja una opcion del menú: "))
  return selec

producto = [["01001", "catshaw 10kg", 1, 25_500],
            ["01002", "Fitformula 10kg", 1, 29_600],
            ["01003", "Cachupin gato 20kg", 1, 18_500],
            ["01004", "purofilete 10kg", 1, 58_600]]
inventario = np.array(producto)

menu_principal()

inventario[0, 2] = 0

print(inventario[0, :])